/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.AdminDB;
import Database.BookingsDB;
import Database.DBManager;
import Database.UsersDB;
import User.Booking;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 @Author Pammi
 */
public class AdminWindow extends JFrame {

    private JTable table;
    private JButton viewUsersBtn, viewBookingsBtn;
    DBManager manager = new DBManager();
    AdminDB admindb = new AdminDB(manager);

    // gets all users and displays them in the table
    public void viewUsers() {
        try (ResultSet rs = admindb.viewallusers()) {
            if (rs == null) {
                JOptionPane.showMessageDialog(this, "No data returned from database");
                return;
            }

            ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();
            DefaultTableModel model = new DefaultTableModel();

            // Clear existing columns
            model.setColumnCount(0);
            model.setRowCount(0);

            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(meta.getColumnName(i));
            }

            while (rs.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }

            UserTable.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading Users: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public AdminWindow() {
        admindb = new AdminDB(manager);
        initComponents();
        makeConnection();
        viewUsers();
    }

    public void AdminWindowMethod() {

    }

    // makes a connection to the database
    public void makeConnection() {
        try {
            DBManager manager = new DBManager();
            manager.getConnection();
        } catch (Exception sqlError) {
            sqlError.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection error");
            System.out.print(JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewUserBTN = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();
        viewBookingsbtn1 = new javax.swing.JButton();
        deleteBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        viewBookingsbtn2 = new javax.swing.JButton();
        makeAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Auckland_Transport_Logo_optimized.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Management Centre");

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        viewUserBTN.setText("View Users");
        viewUserBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserBTNActionPerformed(evt);
            }
        });

        deleteUser.setText("Delete User");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        viewBookingsbtn1.setText("View Bookings");
        viewBookingsbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingsbtn1ActionPerformed(evt);
            }
        });

        deleteBooking.setText("Delete Booking");
        deleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(UserTable);

        viewBookingsbtn2.setText("View Bookings in detail");
        viewBookingsbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingsbtn2ActionPerformed(evt);
            }
        });

        makeAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        makeAdmin.setForeground(new java.awt.Color(204, 0, 51));
        makeAdmin.setText("MAKE ADMIN");
        makeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewBookingsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewBookingsbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(615, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(username_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBookingsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBookingsbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3MouseClicked

    // handles the view users button click
    private void viewUserBTNActionPerformed(java.awt.event.ActionEvent evt) {

        viewUsers();
    }//GEN-LAST:event_viewUserBTNActionPerformed

    // handles the delete user button click
    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = UserTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete");
            return;
        }

        String email = UserTable.getValueAt(selectedRow, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete user with email: " + email + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (admindb.deleteUser(email)) {
                JOptionPane.showMessageDialog(this, "User deleted successfully");
                viewUserBTNActionPerformed(evt); // Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete user");
            }
        }
    }//GEN-LAST:event_deleteUserActionPerformed

    // handles the view bookings button click
    private void viewBookingsbtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try (ResultSet rs = admindb.viewallbookings()) {
            ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();
            DefaultTableModel model = new DefaultTableModel();

            // Clear existing columns
            model.setColumnCount(0);
            model.setRowCount(0);

            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(meta.getColumnName(i));
            }

            while (rs.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }

            UserTable.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading Bookings");
        }
    }//GEN-LAST:event_viewBookingsbtn1ActionPerformed

    // handles the delete booking button click
    private void deleteBookingActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int viewRow = UserTable.getSelectedRow();
        if (viewRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a booking first");
            return;
        }

        int modelRow = UserTable.convertRowIndexToModel(viewRow);
        int bookingId = Integer.parseInt(UserTable.getModel().getValueAt(modelRow, 0).toString());

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Please confirm deletion of booking ID: " + bookingId + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }

// Fixed delete logic
        try {
            BookingsDB bookingsDb = new BookingsDB(new DBManager());

            // Debug: Check if booking exists first
            System.out.println("Trying to delete booking ID: " + bookingId);

            boolean deleted = bookingsDb.deleteBooking(bookingId);

            if (deleted) {
                DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
                model.removeRow(modelRow);
                JOptionPane.showMessageDialog(this, "Booking deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete booking - booking not found");
            }

        } catch (Exception ex) { // Changed from Error to Exception
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting booking: " + ex.getMessage());
        }
    }//GEN-LAST:event_deleteBookingActionPerformed

    // handles the view bookings in detail button click
    private void viewBookingsbtn2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int viewRow = UserTable.getSelectedRow();
        if (viewRow < 0) {
            JOptionPane.showMessageDialog(this,
                    "Select a booking to view in detail");
            return;
        }

        int modelRow = UserTable.convertRowIndexToModel(viewRow);

        String bookingIdStr = UserTable.getModel()
                .getValueAt(modelRow, 0)
                .toString();

        try {

            BookingsDB bookingsDb = new BookingsDB(new DBManager());
            int bookingId = Integer.parseInt(bookingIdStr);
            Booking booking = bookingsDb.getBookingById(bookingId);

            if (booking == null) {
                JOptionPane.showMessageDialog(this, "Booking not found");
                return;
            }

            // Display the booking details
            ReciptPanelAdminView receipt = new ReciptPanelAdminView();
            receipt.displayBooking(booking);
            receipt.setVisible(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid booking ID format");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading booking details: " + ex.getMessage());
        }
    }//GEN-LAST:event_viewBookingsbtn2ActionPerformed

    // handles the make admin button click
    private void makeAdminActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = UserTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a user first");
            return;
        }
        
        int modelRow = UserTable.convertRowIndexToModel(selectedRow);
        String userEmail = UserTable.getModel().getValueAt(modelRow, 1).toString(); 
        String userName = UserTable.getModel().getValueAt(modelRow, 0).toString(); 
        
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Promote " + userName + " (" + userEmail + ") to Admin?",
            "Confirm Promotion",
            JOptionPane.YES_NO_OPTION
        );
        
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }
        UsersDB userDb = new UsersDB(new DBManager()); // assuming you have a UserDB class
        boolean promoted = userDb.updateUserRole(userEmail,"ADMIN");
        if (promoted) {
            DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
            model.setValueAt("ADMIN", modelRow, 2);
            JOptionPane.showMessageDialog(this, 
                    userName + " has been promoted to Admin successfully! 🎉");
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Failed to promote user - user not found");
        }
    }//GEN-LAST:event_makeAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserTable;
    private javax.swing.JButton deleteBooking;
    private javax.swing.JButton deleteUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeAdmin;
    private javax.swing.JLabel username_label2;
    private javax.swing.JButton viewBookingsbtn1;
    private javax.swing.JButton viewBookingsbtn2;
    private javax.swing.JButton viewUserBTN;
    // End of variables declaration//GEN-END:variables
}
