package GUI;

import User.Booking;
import java.awt.Font;
import java.util.List;

/**
 *
 * @author scara
 */
public class ReciptPanel extends javax.swing.JFrame {

    /**
     * Creates new form ReciptPanel
     */
    public ReciptPanel() {

        initComponents();
    }

   public void displayBooking(Booking b) {
        String receipt =
            "Booking Receipt\n" +
            "---------------\n" +
            "ID            : " + b.getBookingId()          + "\n" +
            "Name          : " + b.getName()               + "\n" +
            "Email         : " + b.getEmail()              + "\n" +
            "Date Booked   : " + b.getDateBooked()         + "\n" +
            "Departure Date: " + b.getDepartureDate()      + "\n" +
            "Destination   : " + b.getWhereTo()            + "\n" +
            "Service Type  : " + b.getServiceType()        + "\n" +
            "Price         : $" + String.format("%.2f", b.getPrice()) + "\n" +
            "---------------\n" +
            "Thank you for booking with AT HOP!\n" +
            "Safe travels :)";
        recipt_info.setEditable(false);
        recipt_info.setText(receipt);
    }



    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reciptInfo = new javax.swing.JScrollPane();
        recipt_info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        username_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Auckland_Transport_Logo_optimized.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Your Receipt");

        recipt_info.setColumns(20);
        recipt_info.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        recipt_info.setForeground(new java.awt.Color(0, 51, 204));
        recipt_info.setRows(5);
        recipt_info.setText("Nothing here ATM \n");
        recipt_info.setCaretColor(new java.awt.Color(0, 51, 204));
        recipt_info.setDisabledTextColor(new java.awt.Color(0, 51, 204));
        reciptInfo.setViewportView(recipt_info);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reciptInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)))
                .addGap(26, 26, 26)
                .addComponent(reciptInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciptPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciptPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciptPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciptPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciptPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane reciptInfo;
    private javax.swing.JTextArea recipt_info;
    private javax.swing.JLabel username_label2;
    // End of variables declaration//GEN-END:variables
}
